agent: claude-code

skills:
  - source: https://github.com/pivoshenko/pivoshenko.ai
    skills: "*"

  - source: https://github.com/anthropics/skills
    skills:
      - doc-coauthoring
      - frontend-design

  - source: https://github.com/ferdinandobons/startup-skill
    skills:
      - startup-design
      - startup-competitors
      - startup-positioning
      - startup-pitch

  - source: https://github.com/openai/skills
    skills:
      - name: jupyter-notebook
        path: skills/.curated

  - source: https://github.com/vercel-labs/next-skills
    skills: "*"

  - source: https://github.com/vercel-labs/agent-skills
    skills:
      - web-design-guidelines
      - deploy-to-vercel
