#!/usr/bin/env bash
# drone_audio_edge_test.sh - Edge inference test for DroneAudioCNN ONNX model.
#
# Wraps src/selfsuvis/scripts/drone_audio_edge_infer.py.
# Requirements on host or edge device: numpy scipy onnxruntime
#
# Usage:
#   scripts/audio/drone_audio_edge_test.sh <model.onnx> <audio.wav>
#   scripts/audio/drone_audio_edge_test.sh <model.onnx> <audio.wav> --distance 50
#   scripts/audio/drone_audio_edge_test.sh <model.onnx> <audio.wav> --scan
#
# On edge devices without the full repo, copy these two files instead:
#   drone_audio/<video>/drau_edge_test.py   (generated by pipeline Step 33)
#   drone_audio/<video>/drone_audio_cnn.onnx
# Then run: python drau_edge_test.py drone_audio_cnn.onnx audio.wav

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/shared/common.sh
source "$SCRIPT_DIR/../shared/common.sh"

if [[ $# -lt 2 ]]; then
  echo "Usage: $(basename "$0") <model.onnx> <audio.wav> [options]"
  echo ""
  echo "Options:"
  echo "  --distance M    Simulate drone at M metres (drau physics)"
  echo "  --scan          Test all standard distances and print range table"
  echo "  --threshold T   Confidence threshold (default: 0.5)"
  echo ""
  echo "Example:"
  echo "  $(basename "$0") data/local_runs/my_video/drone_audio/drone_audio_cnn.onnx recording.wav"
  echo "  $(basename "$0") drone_audio_cnn.onnx recording.wav --scan"
  echo "  $(basename "$0") drone_audio_cnn.onnx recording.wav --distance 100"
  exit 1
fi

MODEL="$1"
AUDIO="$2"
shift 2

cd "$PROJECT_ROOT_DIR"

if [[ ! -f ".venv/bin/python" ]]; then
  echo "[error] .venv not found. Run: make venv"
  exit 1
fi

INFER_MODULE="selfsuvis.scripts.drone_audio_edge_infer"

exec .venv/bin/python -m "$INFER_MODULE" "$MODEL" "$AUDIO" "$@"
