FROM python:3.10-slim AS builder

WORKDIR /app
ENV VIRTUAL_ENV=/opt/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN python -m venv "$VIRTUAL_ENV"
COPY requirements/ ./requirements/
RUN pip install --no-cache-dir -r requirements/requirements_test.txt

FROM python:3.10-slim

WORKDIR /app
ENV VIRTUAL_ENV=/opt/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY --from=builder /opt/venv /opt/venv
COPY app ./app
COPY models ./models
COPY pipeline ./pipeline
COPY tests ./tests

ENV PYTHONPATH=/app

CMD ["pytest", "-q"]
