import os
from pathlib import Path

# Paths and CLI defaults.
SSLM_DATA_DIR = Path(os.environ.get("DATA_DIR", "./.data")) / "sslm"
DEFAULT_COMPOSE_FILE = SSLM_DATA_DIR / "docker-compose.generated.yml"
DEFAULT_RESULTS_DIR = SSLM_DATA_DIR / "results"
DEFAULT_SMOKE_OUTPUT = DEFAULT_RESULTS_DIR / "smoke.jsonl"
DEFAULT_LM_EVAL_OUTPUT = DEFAULT_RESULTS_DIR / "lm-eval"
DEFAULT_FINETUNE_OUTPUT = SSLM_DATA_DIR / "finetune" / "qlora.yaml"
DEFAULT_FINETUNE_DATASET = f"jsonl://{Path(os.environ.get('DATA_DIR', './.data')) / 'reasoning_sft.jsonl'}"
DEFAULT_BASELINE_MODEL_ID = "Qwen/Qwen3-8B"
DEFAULT_DASHBOARD_PORT = 8501

CLI_INTERRUPT_EXIT_CODE = 130
CLI_USAGE_EXIT_CODE = 2

# Benchmark defaults.
DEFAULT_SMOKE_MAX_TOKENS = 512
DEFAULT_LM_EVAL_NUM_FEWSHOT = 0
DEFAULT_LM_EVAL_BATCH_SIZE = "4"
DEFAULT_LM_EVAL_MAX_GEN_TOKS = 4096
DEFAULT_LM_EVAL_MAX_LENGTH = 8192
LM_EVAL_TERMINATE_TIMEOUT_S = 10
QUICK_SUITE_NUM_FEWSHOT = 5

# Sample limit for quick/dev benchmark suites. Matches the SSLM_QUICK_LIMIT env
# var used by run-benchmark.sh.
QUICK_SUITE_LIMIT: int = int(os.environ.get("SSLM_QUICK_LIMIT", 10))

# vLLM and model defaults.
DEFAULT_VLLM_IMAGE = "vllm/vllm-openai:latest"
DEFAULT_MODEL_DTYPE = "bfloat16"
DEFAULT_MODEL_QUANTIZATION = "fp8"
DEFAULT_MODEL_MIN_GPU_GB = 12
DEFAULT_MODEL_MAX_LEN = 32768
DEFAULT_MODEL_GPU_MEMORY_UTILIZATION = 0.88
DEFAULT_MODEL_MAX_NUM_SEQS = 4
VLLM_HOST = "0.0.0.0"
VLLM_CONTAINER_PORT = 8000

ZAYA_PORT = 8010
ZAYA_MAX_MODEL_LEN = 8192
ZAYA_GPU_MEMORY_UTILIZATION = 0.88
ZAYA_MIN_GPU_GB = 24
ZAYA_TEMPERATURE = 1.0
ZAYA_TOP_P = 0.95
ZAYA_TOP_K = -1

QWEN3_8B_PORT = 8011
QWEN3_8B_MAX_MODEL_LEN = 8192
QWEN3_8B_GPU_MEMORY_UTILIZATION = 0.75
QWEN3_8B_MIN_GPU_GB = 12

QWEN3_4B_FP8_PORT = 8012
QWEN3_4B_FP8_MAX_MODEL_LEN = 6144
QWEN3_4B_FP8_GPU_MEMORY_UTILIZATION = 0.62
QWEN3_4B_FP8_MAX_NUM_SEQS = 1
QWEN3_4B_FP8_MIN_GPU_GB = 8

# OpenAI-compatible client defaults.
DEFAULT_OPENAI_API_KEY = "EMPTY"
DEFAULT_CHAT_SYSTEM_PROMPT = "You are a careful reasoning assistant. Give concise final answers."
DEFAULT_CHAT_TEMPERATURE = 0.6
DEFAULT_CHAT_TOP_P = 0.95
DEFAULT_CHAT_MAX_TOKENS = DEFAULT_SMOKE_MAX_TOKENS
DEFAULT_CLIENT_TIMEOUT_S = 120.0
HEALTH_REQUEST_TIMEOUT_S = 5.0
MODEL_LIST_TIMEOUT_S = 10.0
HTTP_OK = 200
ENDPOINT_READY_TIMEOUT_S = 300.0
READY_POLL_INTERVAL_S = 5.0
READY_LOG_INTERVAL_S = 30.0

# Docker sidecar defaults.
COMPOSE_USER = "${SSLM_UID:-1000}:${SSLM_GID:-1000}"
COMPOSE_SHM_SIZE = "4g"
COMPOSE_CONTAINER_MEM_LIMIT = "${SSLM_CONTAINER_MEM_LIMIT:-24g}"
COMPOSE_MEM_SWAPPINESS = 0
COMPOSE_HEALTH_INTERVAL = "30s"
COMPOSE_HEALTH_TIMEOUT = "10s"
COMPOSE_HEALTH_RETRIES = 20
COMPOSE_HEALTH_START_PERIOD = "180s"
COMPOSE_GPU_COUNT = 1
CUDA_BUILD_PEAK_GB_PER_JOB = 12
CUDA_BUILD_DEFAULT_CPU_COUNT = 4
CUDA_BUILD_RESERVED_CPUS = 2
CUDA_BUILD_CPU_DIVISOR = 2
MEMINFO_KB_PER_GIB = 1024 * 1024
REMOTE_COMMIT_TIMEOUT_S = 30
DOCKER_LOG_TAIL = 100
COMMIT_DISPLAY_CHARS = 12

# Starter QLoRA recipe defaults.
DEFAULT_QLORA_LORA_R = 16
DEFAULT_QLORA_LORA_ALPHA = 32
DEFAULT_QLORA_LORA_DROPOUT = 0.05
DEFAULT_QLORA_SEQUENCE_LENGTH = 4096
DEFAULT_QLORA_LEARNING_RATE = "2.0e-5"
DEFAULT_QLORA_TRAIN_BATCH_SIZE = 1
DEFAULT_QLORA_GRADIENT_ACCUMULATION_STEPS = 16
DEFAULT_QLORA_TRAIN_EPOCHS = 1
DEFAULT_QLORA_WARMUP_RATIO = 0.03

# GPU preflight.
GPU_QUERY_TIMEOUT_S = 10
NVIDIA_SMI_MIB_PER_GIB = 1024

# Dashboard scoring.
DASHBOARD_SCORE_MULTIPLIER = 100
DASHBOARD_SCORE_DECIMALS = 1
DASHBOARD_HISTORY_SCORE_DECIMALS = 2
